"""
Draw the schema of the four traction motor recovery cases.

    ./.venv/bin/python tools/draw_tractionmotor_cases_overview.py

⚠️ A DOCUMENT, NOT A RUN OUTPUT, which is why it is written to
`documentation/` and not to `figures/`. Everything under `figures/` is
regenerated by 02 and 03 on every run and is gitignored for that reason; this
explains the cases rather than reporting one, so it is version-controlled
alongside the handover.

The numbers in it are the deterministic chain coefficients each case produces
for neodymium at 2030 and 2060. They are typed here rather than read from the
output, because the figure has to draw even when no case has been solved --
if a case's chain changes, this file changes with it.
"""
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch

COM = '#5B7C99'; DIS = '#2E7D5B'; SHR = '#B5651D'
LONG = '#2980B9'; SHORT = '#8E44AD'; SPLIT = '#16A085'; LOST = '#C0392B'

fig, ax = plt.subplots(figsize=(18, 10))
ax.set_xlim(0, 100); ax.set_ylim(0, 62); ax.axis('off')

def box(x, y, w, h, text, colour, alpha=0.15, fs=9, weight='normal', lw=1.6):
    ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle='round,pad=0.4',
                                facecolor=colour, alpha=alpha,
                                edgecolor=colour, linewidth=lw))
    ax.text(x + w/2, y + h/2, text, ha='center', va='center', fontsize=fs,
            weight=weight, linespacing=1.4, color='#111')

def arrow(x1, y1, x2, y2, colour='#555', lw=1.8):
    ax.add_patch(FancyArrowPatch((x1, y1), (x2, y2), arrowstyle='-|>',
                                 mutation_scale=14, color=colour, lw=lw,
                                 shrinkA=3, shrinkB=3))

# ---------------------------------------------------------------- trunk
ax.text(1, 58.5, 'EVERY CASE STARTS HERE', fontsize=9, weight='bold', color=COM)
box(1, 50, 17, 6.5, 'End-of-life BEV\ncollected', COM)
box(1, 41, 17, 6.5, 'Traction motor\nreaches treatment', COM)
arrow(9.5, 50, 9.5, 47.5)
ax.text(9.5, 38.6, 'the one big fork', ha='center', fontsize=9.5,
        weight='bold', style='italic')
arrow(9.5, 41, 9.5, 36.5)
arrow(9.5, 35.5, 23, 44, DIS, 2.4)
arrow(9.5, 35.5, 23, 15, SHR, 2.4)

# ------------------------------------------------------- disassembly arm
ax.text(23, 52.5, 'TAKE IT APART', fontsize=10, weight='bold', color=DIS)
box(23, 44, 17, 7, 'Dehouse,\ndemagnetise,\nextract + mill magnet', DIS)
ax.text(23, 41.6, 'copper, aluminium and steel leave here in all three',
        fontsize=7.8, color='#666', style='italic')
arrow(40, 47.5, 45, 47.5, DIS, 2.2)
ax.text(57, 59.2, 'what happens to the magnet decides the case',
        fontsize=9, style='italic', color='#444', ha='center')

for y, col in [(52, SHORT), (44.5, SPLIT), (37, LONG)]:
    arrow(45, 47.5, 49, y + 3, col, 1.8)

# the three magnet routes
box(49, 52, 22, 6.2, 'SHORT LOOP  ·  hydrogen\nkeeps the alloy whole', SHORT, fs=9)
box(49, 44.5, 22, 6.2, 'SPLIT  ·  a share to each\n(share is an assumption)', SPLIT, fs=9)
box(49, 37, 22, 6.2, 'LONG LOOP  ·  dissolve and\nseparate the elements', LONG, fs=9)

rows = [(52, SHORT, 'tractionmotor_shortloop',
         'new magnet alloy\nNd Pr Dy Tb still together', '0.46', '0.67'),
        (44.5, SPLIT, 'tractionmotor_split',
         'both outputs,\nin whatever share you set', '0.41', '0.66'),
        (37, LONG, 'tractionmotor',
         'separated oxides\nNd · Pr · Dy · Tb apart', '0.41', '0.65')]
for y, col, case, yields, a, b in rows:
    arrow(71, y + 3.1, 75, y + 3.1, col, 1.8)
    box(75, y, 24, 6.2, '', col, alpha=0.08)
    ax.text(76, y + 4.6, case, fontsize=8.4, family='monospace',
            weight='bold', color=col, va='center')
    ax.text(76, y + 2.3, yields, fontsize=8.4, va='center', linespacing=1.4)
    ax.text(98, y + 4.6, f'Nd {a}\u2192{b}', fontsize=9, ha='right',
            color=col, weight='bold', va='center')

# ---------------------------------------------------------- shredder arm
ax.text(23, 21.5, 'SHRED IT WHOLE', fontsize=10, weight='bold', color=SHR)
box(23, 13, 17, 7, 'No magnet removal.\nEverything into\nthe shredder', SHR)
arrow(40, 16.5, 49, 16.5, SHR, 2.2)

box(49, 18.5, 22, 5.2, 'copper · aluminium · steel\nrecovered, much as before',
    SHR, alpha=0.10, fs=8.6)
box(49, 11, 22, 6.2, 'the magnet is dispersed\ninto steel, non-ferrous, residue',
    LOST, alpha=0.13, fs=8.6)
arrow(71, 14.1, 75, 14.1, LOST, 1.8)
box(75, 11, 24, 6.2, '', LOST, alpha=0.08)
ax.text(76, 15.6, 'tractionmotor_shredder', fontsize=8.4, family='monospace',
        weight='bold', color=SHR, va='center')
ax.text(76, 13.3, 'almost nothing\nrecovered as rare earth', fontsize=8.4,
        va='center', linespacing=1.4)
ax.text(98, 15.6, 'Nd 0.02\u21920.27', fontsize=9, ha='right', color=LOST,
        weight='bold', va='center')

# ------------------------------------------------------------- the point
ax.text(1, 9.8, 'WHAT THE FORK COSTS', fontsize=9.5, weight='bold')
ax.text(1, 7.6,
        'Copper, aluminium and steel come back either way.\n'
        'It is the magnet the shredder destroys: 26x less\n'
        'neodymium in 2030.',
        fontsize=8.8, va='top', linespacing=1.5)
ax.text(1, 2.4,
        'Steel is the exception — the shredder recovers MORE\n'
        'of it, 0.72 against 0.60.',
        fontsize=8.8, va='top', linespacing=1.5, color=SHR)

ax.text(61, 5.0, 'Numbers are the share of neodymium in collected motors that comes '
        'back as recovered neodymium, 2030 → 2060.', fontsize=8.6, ha='center',
        color='#444')
ax.text(61, 2.8, 'All coefficients are scenario assumptions from the RAWCLIC recycling '
        'review, not measurements.', fontsize=8.6, ha='center', style='italic',
        color='#A93226')
ax.set_title('The four traction-motor recovery cases', fontsize=15, weight='bold', pad=6)
fig.tight_layout()
fig.savefig('documentation/tractionmotor_cases_overview.png', dpi=160, facecolor='white')
print('ok')
