"""
src/params_io.py
================

Reading and writing `params.xlsx`, the parameter file.

Kept apart from `params_schema.py` (which stays free of I/O) and from
`00_parameters.py` (whose leading digits make it unimportable as a module,
which is exactly why the loading logic cannot live there).

The spreadsheet is the source of truth. `load()` starts from the dataclass
defaults and applies every row over them, so a missing file means defaults and
a missing row means that field's default -- deleting a line can never leave a
stale value behind.
"""
from __future__ import annotations

import os
from typing import Any

import pandas as pd

from src.params_schema import Params, flatten

PARAMS_FILE = 'params.xlsx'
SHEET = 'parameters'


class ParameterError(RuntimeError):
    """Raised when the parameter file cannot be used as written."""


def load(path: str = PARAMS_FILE, *, required: bool = False) -> Params:
    """
    Build a Params from the spreadsheet, falling back to the coded defaults.

    Raises ParameterError -- listing every problem at once rather than the
    first -- if a cell cannot be read or the result does not validate. Failing
    loudly is the point: a parameter file that is silently ignored is worse
    than no parameter file.
    """
    params = Params()
    if not os.path.exists(path):
        if required:
            raise ParameterError(
                f"No parameter file at '{path}'. Create it with:\n"
                f"    ./.venv/bin/python 00_parameters.py")
        return params

    frame = pd.read_excel(path, sheet_name=SHEET)
    missing_columns = {'key', 'value'} - set(frame.columns)
    if missing_columns:
        raise ParameterError(
            f"'{path}' sheet '{SHEET}' has no {', '.join(sorted(missing_columns))} column. "
            f"Found: {', '.join(map(str, frame.columns))}.")

    problems: list[str] = []
    for row_number, (key, value) in enumerate(zip(frame['key'], frame['value']), start=2):
        if pd.isna(key) or not str(key).strip():
            continue
        try:
            params.set(str(key).strip(), value)
        except (KeyError, ValueError) as error:
            problems.append(f'  row {row_number}: {error}')

    problems += [f'  {issue}' for issue in params.validate()]
    if problems:
        raise ParameterError(f"'{path}' cannot be used as written:\n" + '\n'.join(problems))

    return params


def save(params: Params, path: str = PARAMS_FILE) -> pd.DataFrame:
    """Write the register: one row per parameter, name/description/key/value."""
    frame = pd.DataFrame(flatten(params), columns=['name', 'description', 'key', 'value'])
    with pd.ExcelWriter(path, engine='openpyxl') as writer:
        frame.to_excel(writer, sheet_name=SHEET, index=False)
        _widen(writer.sheets[SHEET], frame)
    return frame


def _widen(sheet: Any, frame: pd.DataFrame) -> None:
    """Column widths, so the file is readable the moment it is opened."""
    for index, (column, width) in enumerate(
            zip(frame.columns, (24, 96, 30, 34)), start=1):
        sheet.column_dimensions[chr(64 + index)].width = width
    sheet.freeze_panes = 'A2'


def reference(params: Params) -> str:
    """The same content as Markdown, for documentation/PARAMETER_REFERENCE.md."""
    lines = [
        '# Parameter reference',
        '',
        'Generated by `00_parameters.py` -- do not edit by hand.',
        '',
        'Every setting the model reads, its default, and what changing it does.',
        'The live values are in `params.xlsx`; the defaults below are what applies',
        'when a row is absent or the file does not exist.',
        '',
    ]
    current_section = None
    for name, description, key, value in flatten(params):
        section = key.split('.')[0]
        if section != current_section:
            current_section = section
            lines += ['', f'## `{section}`', '',
                      '| Parameter | Default | What it does |',
                      '|---|---|---|']
        lines.append(f'| `{key}` | `{value}` | {description} |')
    lines.append('')
    return '\n'.join(lines)
